/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dealSol from "./deal.sol";
export type { dealSol };
import type * as realStateSol from "./real-state.sol";
export type { realStateSol };
